# 1. 가볍고 빠른 Node.js 18 알파인 버전 사용
FROM node:18-alpine

# 2. 컨테이너 내부의 작업 폴더를 /app으로 설정
WORKDIR /app

# 3. 최상위 폴더에 있는 package.json과 package-lock.json 복사
COPY package*.json ./

# 4. 패키지 설치 (여기서 알아서 node_modules를 만듭니다)
RUN npm install

# 5. 필요한 폴더와 파일만 쏙쏙 골라서 복사!
COPY cookit_server ./cookit_server
COPY firebase.json ./

# 6. 3000번 포트 열기
EXPOSE 3000

# 7. 서버 실행 명령어 (cookit_server 폴더 안의 app.js 실행)
CMD ["node", "cookit_server/app.js"]